services:
  - type: web
    name: rideshare
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: JWT_SECRET
        generateValue: true
